[__config__]
oldver = "old.json"
newver = "new.json"
keyfile = "keys.toml"

[Autoruns]
source = "regex"
regex = "Autoruns for Windows v([\\d.]+)"
url = "https://raw.githubusercontent.com/MicrosoftDocs/sysinternals/live/sysinternals/downloads/autoruns.md"

[CrystalDiskInfo]
source = "regex"
regex = "<title>CrystalDiskInfo - ([\\d.]+)</title>"
url = "https://osdn.net/projects/crystaldiskinfo/releases/rss"

[DisplayDriverUninstaller]
source = "regex"
regex = "Display Driver Uninstaller Download version ([\\d.]+)"
url = "https://www.guru3d.com/files_rss"

[ExeInfoPE]
source = "regex"
regex = "Version[\\s\\t]*:[\\s\\t]*([\\d.]+)"
url = "https://raw.githubusercontent.com/ExeinfoASL/ASL/master/file_id.diz"

[GPU-Z]
source = "regex"
regex = "<span>[\\s\\t\\n]*v([\\d.]+)[\\s\\t\\n]*</span>"
url = "https://www.techpowerup.com/download/gpu-z/"

[HWiNFO]
source = "regex"
regex = "HWiNFO v([\\d.]+) released"
url = "https://www.hwinfo.com/news.xml/"

[HWMonitor]
source = "regex"
regex = "Version ([\\d.]+) for windows"
url = "https://www.cpuid.com/softwares/hwmonitor.html"

[IRPF]
source = "regex"
regex = "/arquivos/IRPF([\\d]+-[\\d.]+)\\.zip"
url = "https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/download/pgd/dirpf"

[IRPF_XMLs]
# dependencies: coreutils, curl, xmlstarlet
source = "cmd"
cmd = """
if res=$(curl -fsS 'https://downloadirpf.receita.fazenda.gov.br/irpf/2023/irpf/update/latest.xml')
then
  if xml=$(echo "${res}" | xmlstarlet sel -B -t -c '//information/extra/files')
  then
    echo -n "${xml}" | sha256sum | head -c 8
  else
    exit $?
  fi
else
  exit $?
fi
"""

[KeyCastOW]
source = "regex"
encoding = "utf16"
regex = "\"FileVersion\", \"([\\d.]+)\""
url = "https://raw.githubusercontent.com/brookhong/KeyCastOW/master/keycastow.rc"

[LiveTcpUdpWatch]
source = "regex"
regex = "LiveTcpUdpWatch v([\\d.]+)"
url = "https://www.nirsoft.net/utils/live_tcp_udp_watch.html"

[NVIDIA_470]
# Linux drivers only (R470 Legacy Branch)
source = "regex"
regex = "Latest Legacy GPU version \\(470\\.xx series\\): <a .+?>([\\d.]+)</a>"
url = "https://www.nvidia.com/en-us/drivers/unix/"

[NVIDIA_Production]
# Linux drivers only (Production Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=1&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Latest]
# Linux drivers only (New Feature Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=5&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Beta]
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=0&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Vulkan]
source = "regex"
regex = "<b>Linux ([0-9.]+)</b>"
url = "https://developer.nvidia.com/vulkan-driver"

[ProcessExplorer]
source = "regex"
regex = "Process Explorer v([\\d.]+)"
url = "https://raw.githubusercontent.com/MicrosoftDocs/sysinternals/live/sysinternals/downloads/process-explorer.md"

[ProcessMonitor]
source = "regex"
regex = "Process Monitor v([\\d.]+)"
url = "https://raw.githubusercontent.com/MicrosoftDocs/sysinternals/live/sysinternals/downloads/procmon.md"

[SUMo]
source = "regex"
regex = "<h3>SUMo</h3>[\\r\\n\\s]*?<small>Version : <code>([\\d.]+)</code>"
url = "https://www.kcsoftwares.com/?download"

[TeamViewerLinux]
source = "httpheader"
regex = "teamviewer_([0-9.]+)_amd64\\.deb$"
url = "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"

[UnifiedRemoteServer]
source = "httpheader"
regex = "urserver-([0-9.]+)\\.deb$"
url = "https://www.unifiedremote.com/download/linux-x64-deb"

[USBDeview]
source = "regex"
regex = "USBDeview v([\\d.]+)"
url = "https://www.nirsoft.net/utils/usb_devices_view.html"

[vibranceGUI]
source = "regex"
regex = "AssemblyVersion\\(\"([\\d.]+)\"\\)"
url = "https://raw.githubusercontent.com/juv/vibranceGUI/master/vibrance.GUI/Properties/AssemblyInfo.cs"

[Windows10]
source = "regex"
regex = "<h2>Windows 10 .+? Update \\| Version (.+?)</h2>"
url = "https://www.microsoft.com/en-us/software-download/windows10ISO"

[Windows11]
source = "regex"
regex = "\\(Current release: Windows 11 .+? Version ([^)]+)\\)"
url = "https://www.microsoft.com/en-us/software-download/windows11"

[WinRAR]
source = "regex"
regex = "Version ([\\d.]+)[\\r\\n]"
url = "https://www.rarlab.com/rarnew.htm"

[WizTree]
source = "regex"
regex = ">V&nbsp;([\\d.]+)&nbsp;"
url = "https://www.diskanalyzer.com/download"

[X-Ripper]
source = "regex"
regex = "\"softwareVersion\">([\\d.]+)"
url = "https://www.zeus-software.com/downloads/xripper"
