[__config__]
oldver = "old.json"
newver = "new.json"
keyfile = "keys.toml"

[Autoruns]
source = "regex"
regex = "Autoruns for Windows v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns"

[BleachBit]
source = "github"
github = "bleachbit/bleachbit"
use_latest_release = true
prefix = "v"

[CrystalDiskInfo]
source = "regex"
regex = "Download of CrystalDiskInfo ([\\d.]+)"
url = "https://crystalmark.info/redirect.php?product=CrystalDiskInfo"

[DetectItEasy]
source = "github"
github = "horsicq/DIE-engine"
use_latest_release = true

[DisplayDriverUninstaller]
source = "regex"
regex = "Display Driver Uninstaller Download version ([\\d.]+)"
url = "https://www.guru3d.com/files-get/display-driver-uninstaller-download,1.html"

[DriverStoreExplorer]
source = "github"
github = "lostindark/DriverStoreExplorer"
use_latest_release = true
prefix = "v"

[ExeInfoPE]
source = "regex"
regex = "ersion[\\s\\t]+[\\r\\n][\\s\\t]*: ([\\d.]+)"
url = "http://exeinfo.orgfree.com/"

[GPU-Z]
source = "regex"
regex = "TechPowerUp GPU-Z v([\\d.]+)"
url = "https://www.techpowerup.com/download/techpowerup-gpu-z/"

[HashCheck]
source = "github"
github = "gurnec/HashCheck"
use_latest_release = true
prefix = "v"

[HTTPNetworkSniffer]
source = "regex"
regex = "HTTPNetworkSniffer v([\\d.]+)"
url = "https://www.nirsoft.net/utils/http_network_sniffer.html"

[HWiNFO]
source = "regex"
regex = "<dd itemprop=\"softwareVersion\">([\\d.]+)</dd>"
url = "https://www.fosshub.com/HWiNFO.html"

[HWMonitor]
source = "regex"
regex = "Version ([\\d.]+) for windows"
url = "https://www.cpuid.com/softwares/hwmonitor.html"

[IRPF2021]
source = "regex"
regex = "<pkgver>([\\d.]+)</pkgver>"
url = "http://downloadirpf.receita.fazenda.gov.br/irpf/2021/irpf/update/latest.xml"

[IRPF2021_XMLs]
source = "cmd"
cmd = "curl -s 'http://downloadirpf.receita.fazenda.gov.br/irpf/2021/irpf/update/latest.xml' | sed -e '1,8d' | perl -0 -pe 's/\\n\\Z//' | sha1sum | head -c 40"

[KCleaner]
source = "regex"
regex = "<h3>KCleaner</h3>[\\r\\n\\s]*?<small>Version : <code>([\\d.]+)</code>"
url = "https://www.kcsoftwares.com/?download"

[KeyCastOW]
source = "cmd"
cmd = "curl -s 'https://raw.githubusercontent.com/brookhong/KeyCastOW/master/keycastow.rc' | iconv -f utf16 -t utf8 | grep -F 'FileVersion' | grep -Eo '[0-9.]+'"

[LinuxReader]
source = "regex"
regex = "<span>Ver ([\\d.]+), Win</span>"
url = "https://www.diskinternals.com/linux-reader/"

[LiveTcpUdpWatch]
source = "regex"
regex = "LiveTcpUdpWatch v([\\d.]+)"
url = "https://www.nirsoft.net/utils/live_tcp_udp_watch.html"

[NVIDIA_470]
# Linux drivers only (R470 Legacy Branch)!
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=85&pfid=660&osid=12&lid=1&whql=1&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Production]
# Linux drivers only (Productiony Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=1&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Latest]
# Linux drivers only (New Feature Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=5&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Beta]
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=0&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Vulkan]
source = "regex"
regex = "<b>Linux ([0-9.]+)</b>"
url = "https://developer.nvidia.com/vulkan-driver"

[ProcessExplorer]
source = "regex"
regex = "Process Explorer v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer"

[ProcessHacker]
source = "github"
github = "processhacker/processhacker"
use_latest_release = true
prefix = "v"

[ProcessMonitor]
source = "regex"
regex = "Process Monitor v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/procmon"

[ProduKey]
source = "regex"
regex = "ProduKey v([\\d.]+)"
url = "https://www.nirsoft.net/utils/product_cd_key_viewer.html"

[rsmixer]
source = "github"
github = "jantap/rsmixer"
use_max_tag = true
prefix = "v"

[Rufus]
source = "github"
github = "pbatard/rufus"
use_latest_release = true
prefix = "v"

#[ShiginimaLauncher]
#source = "regex"
#regex = "<h1>Shiginima v([\\d.]+)</h1>"
#url = "https://teamshiginima.com/update/"

[SUMo]
source = "regex"
regex = "<h3>SUMo</h3>[\\r\\n\\s]*?<small>Version : <code>([\\d.]+)</code>"
url = "https://www.kcsoftwares.com/?download"

[TeamViewerLinux]
source = "httpheader"
regex = "teamviewer_([0-9.]+)_amd64\\.deb$"
url = "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"

[UnifiedRemoteServer]
source = "httpheader"
regex = "urserver-([0-9.]+)\\.deb$"
url = "https://www.unifiedremote.com/download/linux-x64-deb"

[USBDeview]
source = "regex"
regex = "USBDeview v([\\d.]+)"
url = "https://www.nirsoft.net/utils/usb_devices_view.html"

[vibranceGUI]
source = "regex"
regex = "AssemblyVersion\\(\"([\\d.]+)\"\\)"
url = "https://raw.githubusercontent.com/juv/vibranceGUI/master/vibrance.GUI/Properties/AssemblyInfo.cs"

[WinAuth]
source = "github"
github = "winauth/winauth"
use_latest_release = true

[Windows10]
source = "regex"
regex = "<h2>Windows 10 (.+?) Update</h2>"
url = "https://www.microsoft.com/en-us/software-download/windows10ISO"

[WinRAR]
source = "regex"
regex = "Version ([\\d.]+)[\\r\\n]"
url = "https://rarlab.com/rarnew.htm"

[WizTree]
source = "regex"
regex = ">V&nbsp;([\\d.]+)&nbsp;"
url = "https://wiztreefree.com/download"

[X-Ripper]
source = "regex"
regex = "\"softwareVersion\">([\\d.]+)"
url = "http://www.zeus-software.com/downloads/xripper"
