[__config__]
oldver = "old.json"
newver = "new.json"
keyfile = "keys.toml"

[Autoruns]
source = "regex"
regex = "Autoruns for Windows v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/autorunZ"

[CrystalDiskInfo]
source = "regex"
regex = "Download of CrystalDiskInfo ([\\d.]+)"
url = "https://crystalmark.info/redirect.php?product=CrystalDiskInfo"

[DisplayDriverUninstaller]
source = "regex"
regex = "Display Driver Uninstaller Download version ([\\d.]+)"
url = "https://www.guru3d.com/files-get/display-driver-uninstaller-download,1.html"

[ExeInfoPE]
source = "regex"
regex = "Version[\\s\\t]*:[\\s\\t]*([\\d.]+)"
url = "https://raw.githubusercontent.com/ExeinfoASL/ASL/master/file_id.diz"

[GPU-Z]
source = "regex"
regex = "TechPowerUp GPU-Z v([\\d.]+)"
url = "https://www.techpowerup.com/download/techpowerup-gpu-z/"

[HTTPNetworkSniffer]
source = "regex"
regex = "HTTPNetworkSniffer v([\\d.]+)"
url = "https://www.nirsoft.net/utils/http_network_sniffer.html"

[HWiNFO]
source = "regex"
regex = "<dd itemprop=\"softwareVersion\">([\\d.]+)</dd>"
url = "https://www.fosshub.com/HWiNFO.html"

[HWMonitor]
source = "regex"
regex = "Version ([\\d.]+) for windows"
url = "https://www.cpuid.com/softwares/hwmonitor.html"

[IRPF]
source = "regex"
regex = "/arquivos/IRPF([\\d]+-[\\d.]+)\\.zip"
url = "https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/download/pgd/dirpf"

[IRPF_XMLs]
# dependencies: coreutils, curl, xmlstarlet
source = "cmd"
cmd = """
if res=$(curl -fsS 'https://downloadirpf.receita.fazenda.gov.br/irpf/2023/irpf/update/latest.xml')
then
  if xml=$(echo "${res}" | xmlstarlet sel -B -t -c '//information/extra/files')
  then
    echo -n "${xml}" | sha256sum | head -c 8
  else
    exit $?
  fi
else
  exit $?
fi
"""

[KeyCastOW]
# dependencies: coreutils, curl
source = "cmd"
cmd = """
if res=$(curl -fsS 'https://raw.githubusercontent.com/brookhong/KeyCastOW/master/keycastow.rc')
then
  echo "${res}" | tr -d '\\0' | grep -oPm1 '"FileVersion" *, *"\\K[^"]+'
else
  exit $?
fi
"""

[LinuxReader]
source = "regex"
regex = "<span>Ver ([\\d.]+), Win</span>"
url = "https://www.diskinternals.com/linux-reader/"

[LiveTcpUdpWatch]
source = "regex"
regex = "LiveTcpUdpWatch v([\\d.]+)"
url = "https://www.nirsoft.net/utils/live_tcp_udp_watch.html"

[NVIDIA_470]
# Linux drivers only (R470 Legacy Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=85&pfid=660&osid=12&lid=1&whql=1&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Production]
# Linux drivers only (Production Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=1&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Latest]
# Linux drivers only (New Feature Branch)
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=5&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Beta]
source = "regex"
regex = "<td class=\"gridItem\">([\\d.]+)</td>"
url = "https://www.nvidia.com/Download/processFind.aspx?psid=120&pfid=930&osid=12&lid=1&whql=0&lang=en-us&ctk=0&qnfslb=01"

[NVIDIA_Vulkan]
source = "regex"
regex = "<b>Linux ([0-9.]+)</b>"
url = "https://developer.nvidia.com/vulkan-driver"

[ProcessExplorer]
source = "regex"
regex = "Process Explorer v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer"

[ProcessMonitor]
source = "regex"
regex = "Process Monitor v([\\d.]+)"
url = "https://docs.microsoft.com/en-us/sysinternals/downloads/procmon"

[ProduKey]
source = "regex"
regex = "ProduKey v([\\d.]+)"
url = "https://www.nirsoft.net/utils/product_cd_key_viewer.html"

[SUMo]
source = "regex"
regex = "<h3>SUMo</h3>[\\r\\n\\s]*?<small>Version : <code>([\\d.]+)</code>"
url = "https://www.kcsoftwares.com/?download"

[TeamViewerLinux]
source = "httpheader"
regex = "teamviewer_([0-9.]+)_amd64\\.deb$"
url = "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"

[UnifiedRemoteServer]
source = "httpheader"
regex = "urserver-([0-9.]+)\\.deb$"
url = "https://www.unifiedremote.com/download/linux-x64-deb"

[USBDeview]
source = "regex"
regex = "USBDeview v([\\d.]+)"
url = "https://www.nirsoft.net/utils/usb_devices_view.html"

[vibranceGUI]
source = "regex"
regex = "AssemblyVersion\\(\"([\\d.]+)\"\\)"
url = "https://raw.githubusercontent.com/juv/vibranceGUI/master/vibrance.GUI/Properties/AssemblyInfo.cs"

[Windows10]
source = "regex"
regex = "<h2>Windows 10 .+? Update | Version (.+?)</h2>"
url = "https://www.microsoft.com/en-us/software-download/windows10ISO"

[Windows11]
source = "regex"
regex = "\\(Current release: Windows 11 .+? Version ([^)]+)\\)"
url = "https://www.microsoft.com/en-us/software-download/windows11"

[WinRAR]
source = "regex"
regex = "Version ([\\d.]+)[\\r\\n]"
url = "https://rarlab.com/rarnew.htm"

[WizTree]
source = "regex"
regex = ">V&nbsp;([\\d.]+)&nbsp;"
url = "https://wiztreefree.com/download"

[X-Ripper]
source = "regex"
regex = "\"softwareVersion\">([\\d.]+)"
url = "http://www.zeus-software.com/downloads/xripper"
